# manifolds/empirical.py
import re
import logging
import asyncio
from typing import Dict, Any, Tuple
import mlx.core as mx

from .base import PhysicalManifold
from core.empirical_sandbox import ContainerizedExecutionEngine

logger = logging.getLogger("Sovereign.Empirical")

class EmpiricalManifold(PhysicalManifold):
    """
    Scientific Method Interceptor.
    Routes untrusted code generated by the Daemon to the Docker Sandbox for empirical validation.
    """
    def __init__(self, sovereign_node: Any):
        self._name = "Sovereign_Empirical_Testing"
        self.node = sovereign_node
        self.sandbox = ContainerizedExecutionEngine()
        
        self.execute_pattern = re.compile(r"\[\[EXECUTE:\s*(.*?)\]\]", re.DOTALL)
        self.buffer = ""
        self.buffering = False
        self._telemetry = {"hypotheses_tested": 0}

    @property
    def name(self) -> str:
        return self._name

    def compute_surprise(self, input_ids: mx.array, logits: mx.array) -> Tuple[mx.array, float]:
        return mx.zeros_like(logits), 1.0

    async def _process_execution(self, source_code: str):
        logger.warning("[!] Empirical Hypothesis Generated. Transmitting to Docker Sandbox...")
        result = await self.sandbox.execute_hypothesis(source_code)
        # Push standard output to the hive feedback loop for Daemon ingestion
        await self.node.hive_feedback.put({"agent": "EMPIRICAL_SANDBOX", "result": result})

    def process_stream(self, chunk: str) -> str:
        if not self.buffering:
            if "[" in chunk:
                self.buffering = True
                self.buffer += chunk
                return ""
            return chunk

        self.buffer += chunk
        
        match = self.execute_pattern.search(self.buffer)
        if match:
            source_code = match.group(1).strip()
            self._telemetry["hypotheses_tested"] += 1
            
            asyncio.create_task(self._process_execution(source_code))
            
            remainder = self.buffer[match.end():]
            self.buffer = ""
            self.buffering = False
            return remainder

        if len(self.buffer) > 4096:
            dump = self.buffer
            self.buffer = ""
            self.buffering = False
            return dump

        return ""

    def get_telemetry(self) -> Dict[str, Any]:
        return self._telemetry
